alarm_panel_eventlog:
  fields:
    entity_id:
      required: true
      example: 'alarm_control_panel.visonic_alarm'
      selector:
        entity:
          integration: visonic
          domain: alarm_control_panel
    code:
      example: "1234"
      default: "0000"
      selector:
        text:

alarm_panel_command:
  fields:
    entity_id:
      required: true
      example: 'alarm_control_panel.visonic_alarm'
      selector:
        entity:
          integration: visonic
          domain: alarm_control_panel
    command:
      required: true
      example: 'Disarm'
      selector:
        select:
          options:
            - "Disarm"
            - "Arm Home"
            - "Arm Home Instant"
            - "Arm Away"
            - "Arm Away Instant"
            - "Mute"
            - "Trigger"
            - "Fire"
            - "Emergency"
            - "Panic"
    code:
      required: false
      example: "1234"
      default: "0000"
      selector:
        text:

alarm_panel_reconnect:
  fields:
    entity_id:
      required: true
      example: 'alarm_control_panel.visonic_alarm'
      selector:
        entity:
          integration: visonic
          domain: alarm_control_panel


alarm_panel_x10:
  fields:
    entity_id:
      required: true
      example: 'switch.visonic_x02'
      selector:
        entity:
          integration: visonic
          domain: switch
    x10command:
      required: true
      example: "Off"
      default: "Off"
      selector:
        select:
          options:
            - "Off"
            - "On"
            - "Dimmer"
            - "Brighten"

alarm_sensor_bypass:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: visonic
          domain: binary_sensor
    bypass:
      required: true
      example: "Off"
      selector:
        select:
          options:
            - "On"
            - "Off"
    code:
      required: false
      example: "1234"
      default: "0000"
      selector:
        text:

alarm_sensor_image:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: visonic
          domain: image
