name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: hassfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Test hassfest
        uses: home-assistant/actions/hassfest@master
